/**
 * Creates a vector of length n with initial values generated by the
 * init function.
 *
 * @param n - The length of the vector.
 * @param init - A function that takes an index and returns the initial value for that index.
 * @returns The generated vector.
 */
export default function createVector( n: number, init = ( i: number ) => 0 ): Vector
{
	return Array.from({ length: n }, ( _, i ) =>
		init( i )
	);
}

export type Vector = number[];
